const products = [
  {
    id: 0,
    name: "Born to die",
    price: 75.99,
    tracklist: [
      "Honeymoom",
      "Music to watch boys to",
      "Terrence loves you",
      "God knows i tried",
      "High by the beach",
      "Freak",
      "Art deco",
      "The burnt Norton - interlude",
      "Religion",
      "Salvatore",
      "The blackest day",
      "24",
      "Swan song",
      "Dont let me be misunderstood",
    ],
    image: "honey.png",
  },
  {
    id: 0,
    name: "Ultraviolence",
    price: 69.99,
    tracklist: [
      "Cruel world",
      "Ultraviolence",
      "Shades of cool",
      "Brooklyn baby",
      "West cost",
      "Sad girl",
      "Pretty when you cry",
      "Money power glory",
      "Fucked my way to the top",
      "Old money",
      "The other woman",
      "Black Beauty",
      "Guns and roses",
      "Florida kilos",
    ],
    image: "honey.png",
  },
  {
    id: 0,
    name: "Norman Fucking Rockwell",
    price: 70.99,
    tracklist: [
      "Norman Fucking Rockwell",
      "Mariners apartment complex",
      "Venice bitch",
      "Fuck it i love you",
      "Doin' time",
      "Love song",
      "Cinnamon girl",
      "How to disappear",
      "California",
      "The next best american record",
      "The greatest",
      "Bartender",
      "Happiness is a butterfly",
      "Hope is a dangerous thing for a woman like me to have",
    ],
    image: "honey.png",
  },
  {
    id: 0,
    name: "Born to die - Paradise",
    price: 50.99,
    tracklist: [
      "Ride",
      "American",
      "Cola",
      "Body electric",
      "Blue velvet",
      "Gods&monsters",
      "Yayo",
      "Bel Air",
      "Burning desire",
    ],
    image: "honey.png",
  },
  {
    id: 0,
    name: "Lust for life",
    price: 60.99,
    tracklist: [
      "Love",
      "Lust for life",
      "13 beaches",
      "Cherry",
      "White mustang",
      "Summer bummer",
      "Groupie love",
      "In my feelings",
      "Coachella - woodstock in my mind",
      "God bless america - and all the beautiful women in it",
      "When the world was at war - we kept dancing",
      "Beautiful people beautiful problems",
      "Tomorrow never came",
      "Heroin",
      "Change",
      "Get Free",
    ],
    image: "honey.png",
  },
  {
    id: 0,
    name: "Blue banisters",
    price: 65.99,
    tracklist: [
      "Text book",
      "Blue banisters",
      "Arcadia",
      "Interlude - the trio",
      "Black bathing suit",
      "If you lie down with me",
      "Beautiful",
      "Violets for roses",
      "Dealer",
      "Thunder",
      "Wildflower wildlife",
      "Nectar of the gods",
      "Living legend",
      "Cherry blossom",
      "Sweet carolina",
    ],
    image: "honey.png",
  },
  {
    id: 0,
    name: "Chemtrails over the country club",
    price: 60.99,
    tracklist: [
      "White dress",
      "Chemtrails over the country club",
      "Tulsa Jesus Freak",
      "Let me love you like a woman",
      "Wild at heart",
      "Not all who wander are lost",
      "Yosemite",
      "Breaking up slowly",
      "Dance til we die",
      "For free",
    ],
    image: "honey.png",
  },
  {
    id: 0,
    name: "Did you know that there is a tunnel under ocean boulevard",
    price: 89.99,
    tracklist: [
      "The grants",
      "Did you know that there is a tunnel under ocean boulevard",
      "Sweet",
      "A&W",
      "Judah Smith interlude",
      "Candy Necklace",
      "Jon bastie interlude",
      "Kinstugi",
      "Fingertips",
      "Paris, Texas",
      "Granfather please stand on my fathers shoulders while he's deepsee fishing",
      "Let the light in",
      "Margaret",
      "Fishtail",
      "Peppers",
      "Taco truck x VB",
    ],
    image: "honey.png",
  },
];
